import type { StepEvent } from "./state-machine/types";

/** Internal pipeline progression — tracks where the AI processing stands */
export type ExecutionStatus = "created" | "categorized" | "prioritized" | "completed" | "failed";

/** User-facing workflow status — where the task sits in the user's board */
export type TaskStatus = "backlog" | "in-progress" | "completed";

/** Category assigned by the CategorizeStep */
export interface CategorizedTask {
  category: string;
  subcategory: string;
  confidence: number;
  reasoning: string;
}

/** Priority assigned by the PrioritizeStep */
export interface PrioritizedTask {
  priority: "critical" | "high" | "medium" | "low";
  score: number;
}

/** Action plan generated by the ActionPlanStep */
export interface ActionPlan {
  steps: ActionStep[];
  estimatedComplexity: "trivial" | "simple" | "moderate" | "complex" | "very_complex";
  summary: string;
}

export interface ActionStep {
  order: number;
  action: string;
}

/** A single task item tracked through the pipeline and stored server-side */
export interface TaskItem {
  id: string;
  executionStatus: ExecutionStatus;
  status: TaskStatus;
  title: string;
  description: string;
  domain: string;
  ambiguities: string[];
  urls: string[];
  category?: CategorizedTask;
  priority?: PrioritizedTask;
  actionPlan?: ActionPlan;
  error?: string;
  events: StepEvent[];
  createdAt: number;
  updatedAt: number;
}

/** Paginated API response */
export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

/** POST /api/tasks request body */
export interface SubmitTasksRequest {
  tasks: string[];
}

/** PATCH /api/tasks/[id] request body */
export interface PatchTaskRequest {
  status?: TaskStatus;
  category?: Partial<CategorizedTask>;
  priority?: Partial<PrioritizedTask>;
  actionPlan?: Partial<ActionPlan>;
}
